dataset:
  repo_id: repo_dp
  root: /media/sircesoc/WD_BLACK/lehome/dataset_challenge_merged/top_long_merged

policy:
  type: diffusion
  device: cuda
  push_to_hub: false
  
  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
  
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/dp_top_long
batch_size: 16
steps: 30000
save_freq: 5000
log_freq: 1000

wandb:
  enable: false